// Generated by imageconverter. Please, do not edit!

#ifndef BITMAPDATABASE_HPP
#define BITMAPDATABASE_HPP

#include <touchgfx/hal/Types.hpp>
#include <touchgfx/Bitmap.hpp>

const uint16_t BITMAP_BLACK_ID = 0; // Size: 30x30 pixels
const uint16_t BITMAP_BLUE_ID = 1; // Size: 30x30 pixels
const uint16_t BITMAP_BLUEQ_ID = 2; // Size: 30x30 pixels
const uint16_t BITMAP_GREEN_ID = 3; // Size: 30x30 pixels
const uint16_t BITMAP_RED_ID = 4; // Size: 30x30 pixels
const uint16_t BITMAP_REDQ_ID = 5; // Size: 30x30 pixels
const uint16_t BITMAP_WHITE_ID = 6; // Size: 30x30 pixels

namespace BitmapDatabase
{
#ifndef NO_USING_NAMESPACE_TOUCHGFX
  using namespace touchgfx;
#endif

  class BitmapData;
  const touchgfx::Bitmap::BitmapData* getInstance();
  uint16_t getInstanceSize();
}

#endif
