/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef SCREEN1_VIEW_BASE_HPP
#define SCREEN1_VIEW_BASE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <mvp/View.hpp>
#include <gui/screen1_screen/Screen1Presenter.hpp>
#include <touchgfx/widgets/Image.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/TextArea.hpp>
#include <touchgfx/widgets/Button.hpp>

class Screen1ViewBase : public touchgfx::View<Screen1Presenter>
{
public:
    Screen1ViewBase();
    virtual ~Screen1ViewBase() {}

protected:
    FrontendApplication& application() { 
        return *static_cast<FrontendApplication*>(Application::getInstance()); 
    }

    /*
     * Member Declarations
     */
    touchgfx::Image image1;
    touchgfx::Image image2;
    touchgfx::Image image1_1;
    touchgfx::Image image2_1;
    touchgfx::Image image1_1_1;
    touchgfx::Image image2_1_1;
    touchgfx::Image image2_1_2;
    touchgfx::Image image1_1_1_1;
    touchgfx::Image image1_1_1_2;
    touchgfx::Image image1_1_1_3;
    touchgfx::Image image1_1_1_4;
    touchgfx::Image image1_1_1_5;
    touchgfx::Image image1_1_1_6;
    touchgfx::Image image1_1_1_7;
    touchgfx::Image image1_1_1_8;
    touchgfx::Image image1_1_1_9;
    touchgfx::Image image2_2;
    touchgfx::Image image2_3;
    touchgfx::Image image2_4;
    touchgfx::Image image2_5;
    touchgfx::Image image2_6;
    touchgfx::Image image2_7;
    touchgfx::Image image2_8;
    touchgfx::Image image2_9;
    touchgfx::Image image2_10;
    touchgfx::Image image2_11;
    touchgfx::Image image2_12;
    touchgfx::Image image2_13;
    touchgfx::Image image2_14;
    touchgfx::Image image2_15;
    touchgfx::Image image2_16;
    touchgfx::Image image2_17;
    touchgfx::Image image2_18;
    touchgfx::Image image2_19;
    touchgfx::Image image2_20;
    touchgfx::Image image2_21;
    touchgfx::Image image2_22;
    touchgfx::Image image2_23;
    touchgfx::Image image2_24;
    touchgfx::Image image2_25;
    touchgfx::Image image2_26;
    touchgfx::Image image2_27;
    touchgfx::Image image2_28;
    touchgfx::Image image2_29;
    touchgfx::Image image1_1_1_6_1;
    touchgfx::Image image1_1_1_6_2;
    touchgfx::Image image1_1_1_6_3;
    touchgfx::Image image1_1_1_6_4;
    touchgfx::Image image1_1_1_6_5;
    touchgfx::Image image1_1_1_6_6;
    touchgfx::Image image1_1_1_6_7;
    touchgfx::Image image1_1_1_6_8;
    touchgfx::Image image1_1_1_6_9;
    touchgfx::Image image1_1_1_6_10;
    touchgfx::Image image1_1_1_6_11;
    touchgfx::Image image1_1_1_6_12;
    touchgfx::Image image1_1_1_6_13;
    touchgfx::Image image1_1_1_6_14;
    touchgfx::Image image1_1_1_6_15;
    touchgfx::Image image1_1_1_6_16;
    touchgfx::Image image1_1_1_6_17;
    touchgfx::Image image1_1_1_6_18;
    touchgfx::Image image1_1_1_6_19;
    touchgfx::Image image1_1_1_6_20;
    touchgfx::Box box1;
    touchgfx::TextArea textArea1;
    touchgfx::Button button1;
    touchgfx::Button button1_1;
    touchgfx::Button button1_2;
    touchgfx::Button button1_3;
    touchgfx::Button button1_4;
    touchgfx::Button button1_5;
    touchgfx::Button button1_6;
    touchgfx::Button button1_7;
    touchgfx::Button button1_8;
    touchgfx::Button button1_9;
    touchgfx::Button button1_10;
    touchgfx::Button button1_11;
    touchgfx::Button button2;
    touchgfx::Button button2_1;
    touchgfx::Button button2_2;
    touchgfx::Button button2_3;
    touchgfx::Button button2_4;
    touchgfx::Button button2_5;
    touchgfx::Button button2_6;
    touchgfx::Button button2_7;
    touchgfx::Button button2_8;
    touchgfx::Button button2_9;
    touchgfx::Button button2_10;
    touchgfx::Button button2_11;
    touchgfx::Button button3;
    touchgfx::Button button3_1;
    touchgfx::Button button3_2;
    touchgfx::Button button3_3;
    touchgfx::Button button3_4;
    touchgfx::Button button3_5;
    touchgfx::Button button3_6;
    touchgfx::Button button3_7;
	touchgfx::Button pom;
	touchgfx::Button *pom2;
	Button *tabu[32];
	
private:

    /*
     * Callback Handler Declarations
     */
    void buttonCallbackHandler(const touchgfx::AbstractButton& src);

    /*
     * Callback Declarations
     */
    touchgfx::Callback<Screen1ViewBase, const touchgfx::AbstractButton&> buttonCallback;

};

#endif // SCREEN1_VIEW_BASE_HPP
