/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/screen1_screen/Screen1ViewBase.hpp>
#include "BitmapDatabase.hpp"
#include <touchgfx/Color.hpp>
#include <texts/TextKeysAndLanguages.hpp>
#include <math.h>
#include <cstdlib>

Screen1ViewBase::Screen1ViewBase()  :
    buttonCallback(this, &Screen1ViewBase::buttonCallbackHandler)
{
    image1.setXY(0, 0);
    image1.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image2.setXY(30, 0);
    image2.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image1_1.setXY(60, 0);
    image1_1.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image2_1.setXY(90, 0);
    image2_1.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image1_1_1.setXY(120, 0);
    image1_1_1.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image2_1_1.setXY(150, 0);
    image2_1_1.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_1_2.setXY(210, 0);
    image2_1_2.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image1_1_1_1.setXY(180, 0);
    image1_1_1_1.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_2.setXY(30, 30);
    image1_1_1_2.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_3.setXY(90, 30);
    image1_1_1_3.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_4.setXY(150, 30);
    image1_1_1_4.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_5.setXY(210, 30);
    image1_1_1_5.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6.setXY(0, 60);
    image1_1_1_6.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_7.setXY(60, 60);
    image1_1_1_7.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_8.setXY(120, 60);
    image1_1_1_8.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_9.setXY(180, 60);
    image1_1_1_9.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image2_2.setXY(0, 30);
    image2_2.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_3.setXY(30, 60);
    image2_3.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_4.setXY(60, 30);
    image2_4.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_5.setXY(90, 60);
    image2_5.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_6.setXY(120, 30);
    image2_6.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_7.setXY(150, 60);
    image2_7.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_8.setXY(180, 30);
    image2_8.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_9.setXY(210, 60);
    image2_9.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_10.setXY(0, 90);
    image2_10.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_11.setXY(60, 90);
    image2_11.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_12.setXY(120, 90);
    image2_12.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_13.setXY(180, 90);
    image2_13.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_14.setXY(30, 120);
    image2_14.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_15.setXY(90, 120);
    image2_15.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_16.setXY(150, 120);
    image2_16.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_17.setXY(210, 120);
    image2_17.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_18.setXY(0, 150);
    image2_18.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_19.setXY(60, 150);
    image2_19.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_20.setXY(120, 150);
    image2_20.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_21.setXY(180, 150);
    image2_21.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_22.setXY(30, 180);
    image2_22.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_23.setXY(90, 180);
    image2_23.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_24.setXY(150, 180);
    image2_24.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_25.setXY(210, 180);
    image2_25.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_26.setXY(0, 210);
    image2_26.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_27.setXY(60, 210);
    image2_27.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_28.setXY(120, 210);
    image2_28.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image2_29.setXY(180, 210);
    image2_29.setBitmap(Bitmap(BITMAP_BLACK_ID));

    image1_1_1_6_1.setXY(30, 90);
    image1_1_1_6_1.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_2.setXY(90, 90);
    image1_1_1_6_2.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_3.setXY(150, 90);
    image1_1_1_6_3.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_4.setXY(210, 90);
    image1_1_1_6_4.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_5.setXY(0, 120);
    image1_1_1_6_5.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_6.setXY(60, 120);
    image1_1_1_6_6.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_7.setXY(120, 120);
    image1_1_1_6_7.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_8.setXY(180, 120);
    image1_1_1_6_8.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_9.setXY(30, 150);
    image1_1_1_6_9.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_10.setXY(90, 150);
    image1_1_1_6_10.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_11.setXY(150, 150);
    image1_1_1_6_11.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_12.setXY(210, 150);
    image1_1_1_6_12.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_13.setXY(0, 180);
    image1_1_1_6_13.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_14.setXY(30, 210);
    image1_1_1_6_14.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_15.setXY(60, 180);
    image1_1_1_6_15.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_16.setXY(90, 210);
    image1_1_1_6_16.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_17.setXY(120, 180);
    image1_1_1_6_17.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_18.setXY(150, 210);
    image1_1_1_6_18.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_19.setXY(210, 210);
    image1_1_1_6_19.setBitmap(Bitmap(BITMAP_WHITE_ID));

    image1_1_1_6_20.setXY(180, 180);
    image1_1_1_6_20.setBitmap(Bitmap(BITMAP_WHITE_ID));

    box1.setPosition(0,240,240,80);
    box1.setColor(touchgfx::Color::getColorFrom24BitRGB(10,56,252));

    textArea1.setPosition(15, 240, 195, 80);
    textArea1.setColor(touchgfx::Color::getColorFrom24BitRGB(0,0,0));
    textArea1.setLinespacing(0);
    textArea1.setRotation(TEXT_ROTATE_90);
    textArea1.setTypedText(TypedText(T_TEXTID1));

	pom.setPosition(30, 0, 30, 30);
	pom.setVisible(false);
	pom.setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));

    button1.setPosition(0, 0, 30, 30);
    button1.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1.ustaw(2, 1);
	button1.setAction(buttonCallback);

    button1_1.setPosition(30, 30, 30, 30);
    button1_1.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_1.ustaw(2, 5);
	button1_1.setAction(buttonCallback);

    button1_2.setPosition(0, 60, 30, 30);
    button1_2.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_2.ustaw(2, 2);
	button1_2.setAction(buttonCallback);

    button1_3.setPosition(0, 120, 30, 30);
    button1_3.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_3.ustaw(2, 3);
	button1_3.setAction(buttonCallback);

    button1_4.setPosition(0, 180, 30, 30);
    button1_4.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_4.ustaw(2, 4);
	button1_4.setAction(buttonCallback);

    button1_5.setPosition(60, 0, 30, 30);
    button1_5.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_5.ustaw(2, 9);
	button1_5.setAction(buttonCallback);

    button1_6.setPosition(60, 60, 30, 30);
    button1_6.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
    button1_6.setAction(buttonCallback);
	button1_6.ustaw(2, 10);

    button1_7.setPosition(30, 90, 30, 30);
    button1_7.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_7.ustaw(2, 6);
	button1_7.setAction(buttonCallback);

    button1_8.setPosition(60, 120, 30, 30);
    button1_8.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_8.ustaw(2, 11);
	button1_8.setAction(buttonCallback);

    button1_9.setPosition(30, 150, 30, 30);
    button1_9.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_9.ustaw(2, 7);
	button1_9.setAction(buttonCallback);

    button1_10.setPosition(60, 180, 30, 30);
    button1_10.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_10.ustaw(2, 12);
	button1_10.setAction(buttonCallback);

    button1_11.setPosition(30, 210, 30, 30);
    button1_11.setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
	button1_11.ustaw(2, 8);
	button1_11.setAction(buttonCallback);

    button2.setPosition(210, 30, 30, 30);
    button2.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2.ustaw(0, 29);
	button2.setAction(buttonCallback);

    button2_1.setPosition(180, 0, 30, 30);
    button2_1.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_1.ustaw(0, 25);
	button2_1.setAction(buttonCallback);

    button2_2.setPosition(150, 30, 30, 30);
    button2_2.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_2.ustaw(0, 21);
	button2_2.setAction(buttonCallback);

    button2_3.setPosition(180, 60, 30, 30);
    button2_3.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_3.ustaw(0, 26);
	button2_3.setAction(buttonCallback);

    button2_4.setPosition(210, 90, 30, 30);
    button2_4.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_4.ustaw(0, 30);
	button2_4.setAction(buttonCallback);

    button2_5.setPosition(180, 120, 30, 30);
    button2_5.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_5.ustaw(0, 27);
	button2_5.setAction(buttonCallback);

    button2_6.setPosition(150, 150, 30, 30);
    button2_6.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_6.ustaw(0, 23);
	button2_6.setAction(buttonCallback);

    button2_7.setPosition(210, 150, 30, 30);
    button2_7.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_7.ustaw(0, 31);
	button2_7.setAction(buttonCallback);

    button2_8.setPosition(150, 90, 30, 30);
    button2_8.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_8.ustaw(0, 22);
	button2_8.setAction(buttonCallback);

    button2_9.setPosition(180, 180, 30, 30);
    button2_9.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_9.ustaw(0, 28);
	button2_9.setAction(buttonCallback);

    button2_10.setPosition(210, 210, 30, 30);
    button2_10.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_10.ustaw(0, 32);
	button2_10.setAction(buttonCallback);

    button2_11.setPosition(150, 210, 30, 30);
    button2_11.setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
	button2_11.ustaw(0, 24);
	button2_11.setAction(buttonCallback);

    button3.setPosition(120, 0, 30, 30);
    button3.setVisible(false);
    button3.setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
	button3.ustaw(1, 17);
	button3.setAction(buttonCallback);

    button3_1.setPosition(90, 30, 30, 30);
    button3_1.setVisible(false);
    button3_1.setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
    button3_1.setAction(buttonCallback);
	button3_1.ustaw(1, 13);

    button3_2.setPosition(120, 60, 30, 30);
    button3_2.setVisible(false);
    button3_2.setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
	button3_2.ustaw(1, 18);
	button3_2.setAction(buttonCallback);

    button3_3.setPosition(90, 90, 30, 30);
    button3_3.setVisible(false);
    button3_3.setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
    button3_3.setAction(buttonCallback);
	button3_3.ustaw(1, 14);

    button3_4.setPosition(120, 120, 30, 30);
    button3_4.setVisible(false);
    button3_4.setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
	button3_4.ustaw(1, 19);
	button3_4.setAction(buttonCallback);

    button3_5.setPosition(90, 150, 30, 30);
    button3_5.setVisible(false);
    button3_5.setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
	button3_5.ustaw(1, 15);
	button3_5.setAction(buttonCallback);

    button3_6.setPosition(120, 180, 30, 30);
    button3_6.setVisible(false);
    button3_6.setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
	button3_6.ustaw(1, 20);
	button3_6.setAction(buttonCallback);

    button3_7.setPosition(90, 210, 30, 30);
    button3_7.setVisible(false);
    button3_7.setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
	button3_7.ustaw(1, 16);
	button3_7.setAction(buttonCallback);
    add(image1);
    add(image2);
    add(image1_1);
    add(image2_1);
    add(image1_1_1);
    add(image2_1_1);
    add(image2_1_2);
    add(image1_1_1_1);
    add(image1_1_1_2);
    add(image1_1_1_3);
    add(image1_1_1_4);
    add(image1_1_1_5);
    add(image1_1_1_6);
    add(image1_1_1_7);
    add(image1_1_1_8);
    add(image1_1_1_9);
    add(image2_2);
    add(image2_3);
    add(image2_4);
    add(image2_5);
    add(image2_6);
    add(image2_7);
    add(image2_8);
    add(image2_9);
    add(image2_10);
    add(image2_11);
    add(image2_12);
    add(image2_13);
    add(image2_14);
    add(image2_15);
    add(image2_16);
    add(image2_17);
    add(image2_18);
    add(image2_19);
    add(image2_20);
    add(image2_21);
    add(image2_22);
    add(image2_23);
    add(image2_24);
    add(image2_25);
	add(image2_26);
	add(image2_27);
	add(image2_28);
	add(image2_29);
	add(image1_1_1_6_1);
	add(image1_1_1_6_2);
	add(image1_1_1_6_3);
	add(image1_1_1_6_4);
	add(image1_1_1_6_5);
	add(image1_1_1_6_6);
	add(image1_1_1_6_7);
	add(image1_1_1_6_8);
	add(image1_1_1_6_9);
	add(image1_1_1_6_10);
	add(image1_1_1_6_11);
	add(image1_1_1_6_12);
	add(image1_1_1_6_13);
	add(image1_1_1_6_14);
	add(image1_1_1_6_15);
	add(image1_1_1_6_16);
	add(image1_1_1_6_17);
	add(image1_1_1_6_18);
	add(image1_1_1_6_19);
	add(image1_1_1_6_20);
	add(box1);
	add(textArea1);
	add(button1);
	add(button1_1);
	add(button1_2);
	add(button1_3);
	add(button1_4);
	add(button1_5);
	add(button1_6);
	add(button1_7);
	add(button1_8);
	add(button1_9);
	add(button1_10);
	add(button1_11);
	add(button2);
	add(button2_1);
	add(button2_2);
	add(button2_3);
	add(button2_4);
	add(button2_5);
	add(button2_6);
	add(button2_7);
	add(button2_8);
	add(button2_9);
	add(button2_10);
	add(button2_11);
	add(button3);
	add(button3_1);
	add(button3_2);
	add(button3_3);
	add(button3_4);
	add(button3_5);
	add(button3_6);
	add(button3_7);
	add(pom);
	tabu[0] = &button1;
	tabu[1] = &button1_2;
	tabu[2] = &button1_3;
	tabu[3] = &button1_4;
	tabu[4] = &button1_1;
	tabu[5] = &button1_7;
	tabu[6] = &button1_9;
	tabu[7] = &button1_11;
	tabu[8] = &button1_5;
	tabu[9] = &button1_6;
	tabu[10] = &button1_8;
	tabu[11] = &button1_10;
	tabu[12] = &button3_1;
	tabu[13] = &button3_3;
	tabu[14] = &button3_5;
	tabu[15] = &button3_7;
	tabu[16] = &button3;
	tabu[17] = &button3_2;
	tabu[18] = &button3_4;
	tabu[19] = &button3_6;
	tabu[20] = &button2_2;
	tabu[21] = &button2_8;
	tabu[22] = &button2_6;
	tabu[23] = &button2_11;
	tabu[24] = &button2_1;
	tabu[25] = &button2_3;
	tabu[26] = &button2_5;
	tabu[27] = &button2_9;
	tabu[28] = &button2;
	tabu[29] = &button2_4;
	tabu[30] = &button2_7;
	tabu[31] = &button2_10;
}

void Screen1ViewBase::buttonCallbackHandler(const touchgfx::AbstractButton& src)
{
	for (int i = 0; i < 32; i++)
	{
		if (&src == tabu[i])
		{
			if ((*tabu[i]).getkrolowa() && (*tabu[i]).getkolor()!=1) // królówki.
			{
				//pierwszy klik 
				if (pom.getklik() == false)
				{
					pom.setost(i);
					(*tabu[i]).setVisible(false);
					(*tabu[i]).invalidate();
					if (i == 0 || i == 1 || i == 2 || i == 3 || i==8 || i == 9 || i == 10 || i == 11 || i==16 || i == 17 || i == 18 || i == 19 || i==24 || i == 25 || i == 26 || i == 27)
					{
						int j = 1, k = 0, l = 4, suma = 0;
						if (i != 0 && i != 1 && i != 2 && i != 3)
						{
							do
							{
								suma = suma + l;
								if (k == 1 && (*tabu[i - suma]).getkolor() != 1) break;
								else if ((*tabu[i - suma]).getkolor() == (*tabu[pom.getostatni()]).getkolor()) break;
								else if (k == 1 && (*tabu[i - suma]).getkolor() == 1)
								{
									(*tabu[i - suma]).setVisible(true);
									(*tabu[i - suma]).invalidate();
									break;
								}
								if ((*tabu[i - suma]).getkolor() != 1) k++;
								else
								{
									(*tabu[i - suma]).setVisible(true);
									(*tabu[i - suma]).invalidate();
								}
								if (j % 2 == 1) l = 3;
								else l = 4;
								j++;
							} while ((i - suma != 1) && (i - suma != 2) && (i - suma != 3) && (i - suma != 7) && (i - suma != 15) && (i - suma != 23));
						}
						j = 1; k = 0; l = 5; suma = 0;
						if (i != 0 && i != 1 && i != 2 && i != 3 && i!=8 && i!=16 && i!=24)
						{
							do
							{
								suma = suma + l;
								if (k == 1 && (*tabu[i - suma]).getkolor() != 1) break;
								else if ((*tabu[i - suma]).getkolor() == (*tabu[pom.getostatni()]).getkolor()) break;
								else if (k == 1 && (*tabu[i - suma]).getkolor() == 1)
								{
									(*tabu[i - suma]).setVisible(true);
									(*tabu[i - suma]).invalidate();
									break;
								}
								if ((*tabu[i - suma]).getkolor() != 1) k++;
								else
								{
									(*tabu[i - suma]).setVisible(true);
									(*tabu[i - suma]).invalidate();
								}
								if (j % 2 == 1) l = 4;
								else l = 5;
								j++;
							} while ((i - suma != 16) && (i - suma != 8) && (i - suma != 0) && (i - suma != 1) && (i - suma != 2));
						}
						j = 1; k = 0; l = 3; suma = 0;
						if (i != 24 && i != 16 && i != 8 && i != 0)
						{
							do
							{
								suma = suma + l;
								if (k == 1 && (*tabu[i + suma]).getkolor() != 1) break;
								else if ((*tabu[i + suma]).getkolor() == (*tabu[pom.getostatni()]).getkolor()) break;
								else if (k == 1 && (*tabu[i + suma]).getkolor() == 1)
								{
									(*tabu[i + suma]).setVisible(true);
									(*tabu[i + suma]).invalidate();
									break;
								}
								if ((*tabu[i + suma]).getkolor() != 1) k++;
								else
								{
									(*tabu[i + suma]).setVisible(true);
									(*tabu[i + suma]).invalidate();
								}
								if (j % 2 == 1) l = 4;
								else l = 3;
								j++;
							} while ((i + suma != 24) && (i + suma != 16) && (i + suma != 8) && (i + suma != 28) && (i + suma != 29) && (i + suma != 30));
						}
						j = 1; k = 0; l = 4; suma = 0;
						do
						{
							suma = suma + l;
							if (k == 1 && (*tabu[i + suma]).getkolor() != 1) break;
							else if ((*tabu[i + suma]).getkolor() == (*tabu[pom.getostatni()]).getkolor()) break;
							else if (k == 1 && (*tabu[i + suma]).getkolor() == 1)
							{
								(*tabu[i + suma]).setVisible(true);
								(*tabu[i + suma]).invalidate();
								break;
							}
							if ((*tabu[i + suma]).getkolor() != 1) k++;
							else
							{
								(*tabu[i + suma]).setVisible(true);
								(*tabu[i + suma]).invalidate();
							}
							if (j % 2 == 1) l = 5;
							else l = 4;
							j++;
						} while ((i + suma != 28) && (i + suma != 29) && (i + suma != 30) && (i + suma != 31) && (i + suma != 23) && (i + suma != 15) && (i + suma != 7));
						pom.setwykt();
					}
					else
					{
						int j = 1, k = 0, l = 4, suma = 0;
						do
						{
							suma = suma + l;
							if (k == 1 && (*tabu[i - suma]).getkolor() != 1) break;
							else if ((*tabu[i - suma]).getkolor() == (*tabu[pom.getostatni()]).getkolor()) break;
							else if (k == 1 && (*tabu[i - suma]).getkolor() == 1)
							{
								(*tabu[i - suma]).setVisible(true);
								(*tabu[i - suma]).invalidate();
								break;
							}
							if ((*tabu[i - suma]).getkolor() != 1) k++;
							else
							{
								(*tabu[i - suma]).setVisible(true);
								(*tabu[i - suma]).invalidate();
							}
							if (j % 2 == 1) l = 5;
							else l = 4;
							j++;
						} while ((i - suma != 1) && (i - suma != 2) && (i - suma != 3) && (i - suma != 0) && (i - suma != 8) && (i - suma != 16) && (i - suma != 24));
						j = 1, k = 0, l = 3, suma = 0;
						if (i != 7 && i != 15 && i != 23 && i != 31)
						{
							do
							{
								suma = suma + l;
								if (k == 1 && (*tabu[i - suma]).getkolor() != 1) break;
								else if ((*tabu[i - suma]).getkolor() == (*tabu[pom.getostatni()]).getkolor()) break;
								else if (k == 1 && (*tabu[i - suma]).getkolor() == 1)
								{
									(*tabu[i - suma]).setVisible(true);
									(*tabu[i - suma]).invalidate();
									break;
								}
								if ((*tabu[i - suma]).getkolor() != 1) k++;
								else
								{
									(*tabu[i - suma]).setVisible(true);
									(*tabu[i - suma]).invalidate();
								}
								if (j % 2 == 1) l = 4;
								else l = 3;
								j++;
							} while ((i - suma != 1) && (i - suma != 2) && (i - suma != 3) && (i - suma != 7) && (i - suma != 15) && (i - suma != 23));
						}
						j = 1; k = 0; l = 4; suma = 0;
						if (i != 28 && i != 29 && i != 30 && i != 31)
						{
							do
							{
								suma = suma + l;
								if (k == 1 && (*tabu[i + suma]).getkolor() != 1) break;
								else if ((*tabu[i + suma]).getkolor() == (*tabu[pom.getostatni()]).getkolor()) break;
								else if (k == 1 && (*tabu[i + suma]).getkolor() == 1)
								{
									(*tabu[i + suma]).setVisible(true);
									(*tabu[i + suma]).invalidate();
									break;
								}
								if ((*tabu[i + suma]).getkolor() != 1) k++;
								else
								{
									(*tabu[i + suma]).setVisible(true);
									(*tabu[i + suma]).invalidate();
								}
								if (j % 2 == 1) l = 3;
								else l = 4;
								j++;
							} while ((i + suma != 24) && (i + suma != 16) && (i + suma != 8) && (i + suma != 28) && (i + suma != 29) && (i + suma != 30));
						}
						j = 1; k = 0; l = 5; suma = 0;
						if (i != 28 && i != 29 && i != 30 && i != 31 && i != 23 && i != 15 && i != 7)
						{
							do
							{
								suma = suma + l;
								if (k == 1 && (*tabu[i + suma]).getkolor() != 1) break;
								else if ((*tabu[i + suma]).getkolor() == (*tabu[pom.getostatni()]).getkolor()) break;
								else if (k == 1 && (*tabu[i + suma]).getkolor() == 1)
								{
									(*tabu[i + suma]).setVisible(true);
									(*tabu[i + suma]).invalidate();
									break;
								}
								if ((*tabu[i + suma]).getkolor() != 1) k++;
								else
								{
									(*tabu[i + suma]).setVisible(true);
									(*tabu[i + suma]).invalidate();
								}
								if (j % 2 == 1) l = 4;
								else l = 5;
								j++;
							} while ((i + suma != 29) && (i + suma != 30) && (i + suma != 31) && (i + suma != 23) && (i + suma != 15));
						}
						pom.setwykt();
					}
				}
			}
			else if (((*tabu[pom.getostatni()]).getkrolowa() == true) && (pom.getklik() == true)) // drugi klik krolowej
			{
				if ((*tabu[i]).getkolor() == 1)
				{
					if ((*tabu[pom.getostatni()]).getkolor() == 2)
					{
						(*tabu[i]).setkolor(2);
						(*tabu[i]).setBitmaps(Bitmap(BITMAP_BLUEQ_ID), Bitmap(BITMAP_BLUEQ_ID));
						(*tabu[i]).setkrolowa();
					}
					else if ((*tabu[pom.getostatni()]).getkolor() == 0)
					{
						(*tabu[i]).setkolor(0);
						(*tabu[i]).setBitmaps(Bitmap(BITMAP_REDQ_ID), Bitmap(BITMAP_REDQ_ID));
						(*tabu[i]).setkrolowa();
					}
					(*tabu[pom.getostatni()]).setkolor(1);
					(*tabu[pom.getostatni()]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
					(*tabu[pom.getostatni()]).setkrolowaf();
					if (pom.getostatni() > i) // zbijanie krolowka
					{
						if (i == 0 || i == 1 || i == 2 || i == 3 || i == 8 || i == 9 || i == 10 || i == 11 || i == 16 || i == 17 || i == 18 || i == 19 || i == 24 || i == 25 || i == 26 || i == 27)
						{
							if ((pom.getostatni() - 7 == i) || (pom.getostatni() - 10 == i) || (pom.getostatni() - 14 == i) || (pom.getostatni() - 17 == i) || (pom.getostatni() - 21 == i))
							{
								if ((*tabu[i + 3]).getkolor() != 1)
								{
									(*tabu[i + 3]).setkolor(1);
									(*tabu[i + 3]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
									(*tabu[i + 3]).setVisible(false);
									(*tabu[i + 3]).invalidate();
									(*tabu[i + 3]).setkrolowaf();
								}
							}
							else if ((pom.getostatni() - 9 == i) || (pom.getostatni() - 13 == i) || (pom.getostatni() - 18 == i) || (pom.getostatni() - 22 == i) || (pom.getostatni() - 27 == i) || (pom.getostatni() - 31 == i))
							{
								if ((*tabu[i + 4]).getkolor() != 1)
								{
									(*tabu[i + 4]).setkolor(1);
									(*tabu[i + 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
									(*tabu[i + 4]).setVisible(false);
									(*tabu[i + 4]).invalidate();
									(*tabu[i + 4]).setkrolowaf();
								}
							}
						}
						else
						{
							if ((pom.getostatni() - 7 == i) || (pom.getostatni() - 11 == i) || (pom.getostatni() - 14 == i) || (pom.getostatni() - 18 == i) || (pom.getostatni() - 21 == i))
							{
								if ((*tabu[i + 4]).getkolor() != 1)
								{
									(*tabu[i + 4]).setkolor(1);
									(*tabu[i + 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
									(*tabu[i + 4]).setVisible(false);
									(*tabu[i + 4]).invalidate();
									(*tabu[i + 4]).setkrolowaf();
								}
							}
							else if ((pom.getostatni() - 9 == i) || (pom.getostatni() - 14 == i) || (pom.getostatni() - 18 == i) || (pom.getostatni() - 23 == i) || (pom.getostatni() - 27 == i))
							{
								if ((*tabu[i + 5]).getkolor() != 1)
								{
									(*tabu[i + 5]).setkolor(1);
									(*tabu[i + 5]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
									(*tabu[i + 5]).setVisible(false);
									(*tabu[i + 5]).invalidate();
									(*tabu[i + 5]).setkrolowaf();
								}
							}
						}
					}
					else if (pom.getostatni() < i)
					{
						if (i == 0 || i == 1 || i == 2 || i == 3 || i == 8 || i == 9 || i == 10 || i == 11 || i == 16 || i == 17 || i == 18 || i == 19 || i == 24 || i == 25 || i == 26 || i == 27)
						{
							if ((pom.getostatni() + 7 == i) || (pom.getostatni() + 11 == i) || (pom.getostatni() + 14 == i) || (pom.getostatni() + 18 == i) || (pom.getostatni() + 21 == i))
							{
								if ((*tabu[i - 4]).getkolor() != 1)
								{
									(*tabu[i - 4]).setkolor(1);
									(*tabu[i - 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
									(*tabu[i - 4]).setVisible(false);
									(*tabu[i - 4]).invalidate();
									(*tabu[i - 4]).setkrolowaf();
								}
							}
							else if ((pom.getostatni() + 9 == i) || (pom.getostatni() + 14 == i) || (pom.getostatni() + 18 == i) || (pom.getostatni() + 23 == i) || (pom.getostatni() + 27 == i))
							{
								if ((*tabu[i - 5]).getkolor() != 1)
								{
									(*tabu[i - 5]).setkolor(1);
									(*tabu[i - 5]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
									(*tabu[i - 5]).setVisible(false);
									(*tabu[i - 5]).invalidate();
									(*tabu[i - 5]).setkrolowaf();
								}
							}
						}
						else
						{
							if ((pom.getostatni() + 7 == i) || (pom.getostatni() + 10 == i) || (pom.getostatni() + 14 == i) || (pom.getostatni() + 17 == i) || (pom.getostatni() + 21 == i))
							{
								if ((*tabu[i - 3]).getkolor() != 1)
								{
									(*tabu[i - 3]).setkolor(1);
									(*tabu[i - 3]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
									(*tabu[i - 3]).setVisible(false);
									(*tabu[i - 3]).invalidate();
									(*tabu[i - 3]).setkrolowaf();
								}
							}
							else if ((pom.getostatni() + 9 == i) || (pom.getostatni() + 13 == i) || (pom.getostatni() + 18 == i) || (pom.getostatni() + 22 == i) || (pom.getostatni() + 27 == i) || (pom.getostatni() + 31 == i))
							{
								if ((*tabu[i - 4]).getkolor() != 1)
								{
									(*tabu[i - 4]).setkolor(1);
									(*tabu[i - 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
									(*tabu[i - 4]).setVisible(false);
									(*tabu[i - 4]).invalidate();
									(*tabu[i - 4]).setkrolowaf();
								}
							}
						}
					}
					for (int i = 0; i < 32; i++)
					{
						if ((*tabu[i]).getkolor() == 1)
						{
							(*tabu[i]).setVisible(false);
							(*tabu[i]).invalidate();
						}
					}
					pom.setwykt();
				}
				else
				{
					pom.setwykf();
					pom.setklikf();
					for (int i = 0; i < 32; i++)
					{
						if ((*tabu[i]).getkolor() == 1)
						{
							(*tabu[i]).setVisible(false);
							(*tabu[i]).invalidate();
						}
					}
				}
			}
			//dla niebieskiego
			else if ((((*tabu[i]).getkolor() == 2) && (pom.getklik() == false)) || ((pom.getklik() == true) && ((*tabu[pom.getostatni()]).getkolor()==2)))
			{
				//pierwszy klik
				if (pom.getklik() == false)
				{
					pom.setost(i);
					(*tabu[i]).setVisible(false);
					(*tabu[i]).invalidate();
					//jedna sciana boczna
					if (i % 8 == 0)
					{	
						if (i == 0)
						{
							if (((*tabu[i + 4]).getkolor() == 0) && (i < 24) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
							else if ((*tabu[i + 4]).getkolor() == 1)
							{
								(*tabu[i + 4]).setVisible(true);
								(*tabu[i + 4]).invalidate();
								pom.setwykt();
							}
						}
						else if ((((*tabu[i - 4]).getkolor() == 0) && (i > 7) && ((*tabu[i - 7]).getkolor() == 1)) || (((*tabu[i + 4]).getkolor() == 0) && (i < 24) && ((*tabu[i + 9]).getkolor() == 1)))
						{
							if (((*tabu[i + 4]).getkolor() == 0) && (i < 24) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 4]).getkolor() == 0) && (i > 7) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
						}
						else if ((*tabu[i + 4]).getkolor() == 1)
						{
							(*tabu[i + 4]).setVisible(true);
							(*tabu[i + 4]).invalidate();
							pom.setwykt();
						}
					}
					//druga sciana boczna
					else if (i == 7 || i == 15 || i == 23)
					{
						if ((((*tabu[i + 4]).getkolor() == 0) && (i < 24) && ((*tabu[i + 7]).getkolor() == 1)) || (((*tabu[i - 4]).getkolor() == 0) && (i > 7) && ((*tabu[i - 9]).getkolor() == 1)))
						{
							if (((*tabu[i + 4]).getkolor() == 0) && (i < 24) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 4]).getkolor() == 0) && (i > 7) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
						}
						else if ((*tabu[i + 4]).getkolor() == 1)
						{
							(*tabu[i + 4]).setVisible(true);
							(*tabu[i + 4]).invalidate();
							pom.setwykt();
						}
					}
					//druga kolumna od lewej
					else if (i == 4 || i==12 || i==20)
					{
						if ((((*tabu[i + 5]).getkolor() == 0) && (i < 24) && ((*tabu[i + 9]).getkolor() == 1)) || (((*tabu[i - 3]).getkolor() == 0) && (i > 7) && ((*tabu[i - 7]).getkolor() == 1)))
						{
							if (((*tabu[i - 3]).getkolor() == 0) && (i > 7) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 5]).getkolor() == 0) && (i < 24) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i + 4]).getkolor() == 1) || ((*tabu[i + 5]).getkolor() == 1))
						{
							if ((*tabu[i + 4]).getkolor() == 1)
							{
								(*tabu[i + 4]).setVisible(true);
								(*tabu[i + 4]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i + 5]).getkolor() == 1)
							{
								(*tabu[i + 5]).setVisible(true);
								(*tabu[i + 5]).invalidate();
								pom.setwykt();
							}
						}
					}
					//druga kolumna od prawej
					else if (i == 3 || i == 11 || i == 19 || i==27)
					{
						if (i == 3)
						{
							if (((*tabu[i + 3]).getkolor() == 0) && (i < 24) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
							else if (((*tabu[i + 4]).getkolor() == 1) || ((*tabu[i + 3]).getkolor() == 1))
							{
								if ((*tabu[i + 4]).getkolor() == 1)
								{
									(*tabu[i + 4]).setVisible(true);
									(*tabu[i + 4]).invalidate();
									pom.setwykt();
								}
								if ((*tabu[i + 3]).getkolor() == 1)
								{
									(*tabu[i + 3]).setVisible(true);
									(*tabu[i + 3]).invalidate();
									pom.setwykt();
								}
							}
						}
						else if ((((*tabu[i + 3]).getkolor() == 0) && (i < 24) && ((*tabu[i + 7]).getkolor() == 1)) || (((*tabu[i - 5]).getkolor() == 0) && (i > 7) && ((*tabu[i - 9]).getkolor() == 1)))
						{
							if (((*tabu[i + 3]).getkolor() == 0) && (i < 24) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 5]).getkolor() == 0) && (i > 7) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i + 4]).getkolor() == 1) || ((*tabu[i + 3]).getkolor() == 1))
						{
							if ((*tabu[i + 4]).getkolor() == 1)
							{
								(*tabu[i + 4]).setVisible(true);
								(*tabu[i + 4]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i + 3]).getkolor() == 1)
							{
								(*tabu[i + 3]).setVisible(true);
								(*tabu[i + 3]).invalidate();
								pom.setwykt();
							}
						}
					}
					//start niebieskich
					else if (i == 1 || i == 2)
					{
						if ((((*tabu[i + 4]).getkolor() == 0) && ((*tabu[i + 9]).getkolor() == 1)) || (((*tabu[i + 3]).getkolor() == 0) && ((*tabu[i + 7]).getkolor() == 1)))
						{
							if (((*tabu[i + 3]).getkolor() == 0) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 4]).getkolor() == 0) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i + 3]).getkolor() == 1) || ((*tabu[i + 4]).getkolor() == 1))
						{
							if ((*tabu[i + 3]).getkolor() == 1)
							{
								(*tabu[i + 3]).setVisible(true);
								(*tabu[i + 3]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i + 4]).getkolor() == 1)
							{
								(*tabu[i + 4]).setVisible(true);
								(*tabu[i + 4]).invalidate();
								pom.setwykt();
							}
						}
					}
					//start niebieskich, linia druga
					else if (i == 5 || i == 6)
					{
						if ((((*tabu[i + 4]).getkolor() == 0) && ((*tabu[i + 7]).getkolor() == 1)) || (((*tabu[i + 5]).getkolor() == 0) && ((*tabu[i + 9]).getkolor() == 1)))
						{
							if (((*tabu[i + 4]).getkolor() == 0) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 5]).getkolor() == 0) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i + 4]).getkolor() == 1) || ((*tabu[i + 5]).getkolor() == 1))
						{
							if ((*tabu[i + 4]).getkolor() == 1)
							{
								(*tabu[i + 4]).setVisible(true);
								(*tabu[i + 4]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i + 5]).getkolor() == 1)
							{
								(*tabu[i + 5]).setVisible(true);
								(*tabu[i + 5]).invalidate();
								pom.setwykt();
							}
						}						
					}
					//druga linia od konca
					else if (i == 25 || i == 26)
					{
						if ((((*tabu[i - 5]).getkolor() == 0) && ((*tabu[i - 9]).getkolor() == 1)) || (((*tabu[i - 4]).getkolor() == 0) && ((*tabu[i - 7]).getkolor() == 1)))
						{
							if (((*tabu[i - 4]).getkolor() == 0) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 5]).getkolor() == 0) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i + 3]).getkolor() == 1) || ((*tabu[i + 4]).getkolor() == 1))
						{
							if ((*tabu[i + 3]).getkolor() == 1)
							{
								(*tabu[i + 3]).setVisible(true);
								(*tabu[i + 3]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i + 4]).getkolor() == 1)
							{
								(*tabu[i + 4]).setVisible(true);
								(*tabu[i + 4]).invalidate();
								pom.setwykt();
							}
						}
					}
					//srodek co 3 i 4
					else if (i == 9 || i == 10 || i == 17 || i == 18)
					{
						if ((((*tabu[i + 3]).getkolor() == 0) && ((*tabu[i + 7]).getkolor() == 1)) || (((*tabu[i + 4]).getkolor() == 0) && ((*tabu[i + 9]).getkolor() == 1)) || (((*tabu[i - 5]).getkolor() == 0) && ((*tabu[i - 9]).getkolor() == 1)) || (((*tabu[i - 4]).getkolor() == 0) && ((*tabu[i - 7]).getkolor() == 1)))
						{
							if (((*tabu[i + 3]).getkolor() == 0) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 4]).getkolor() == 0) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 5]).getkolor() == 0) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 4]).getkolor() == 0) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i + 3]).getkolor() == 1) || ((*tabu[i + 4]).getkolor() == 1))
						{
							if ((*tabu[i + 3]).getkolor() == 1)
							{
								(*tabu[i + 3]).setVisible(true);
								(*tabu[i + 3]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i + 4]).getkolor() == 1)
							{
								(*tabu[i + 4]).setVisible(true);
								(*tabu[i + 4]).invalidate();
								pom.setwykt();
							}
						}
					}
					//srodek co 4 i 5
					else if (i == 13 || i == 14 || i == 21 || i == 22)
					{
						if ((((*tabu[i + 4]).getkolor() == 0) && ((*tabu[i + 7]).getkolor() == 1)) || (((*tabu[i + 5]).getkolor() == 0) && ((*tabu[i + 9]).getkolor() == 1)) || (((*tabu[i - 3]).getkolor() == 0) && ((*tabu[i - 7]).getkolor() == 1)) || (((*tabu[i - 4]).getkolor() == 0) && ((*tabu[i - 9]).getkolor() == 1)))
						{
							if (((*tabu[i + 4]).getkolor() == 0) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 5]).getkolor() == 0) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 3]).getkolor() == 0) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 4]).getkolor() == 0) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i + 4]).getkolor() == 1) || ((*tabu[i + 5]).getkolor() == 1))
						{
							if ((*tabu[i + 4]).getkolor() == 1)
							{
								(*tabu[i + 4]).setVisible(true);
								(*tabu[i + 4]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i + 5]).getkolor() == 1)
							{
								(*tabu[i + 5]).setVisible(true);
								(*tabu[i + 5]).invalidate();
								pom.setwykt();
							}
						}
					}
				}
				//drugi klik
				else if (pom.getklik() == true)
				{
					if ((*tabu[i]).getkolor() == 1)                //ruch
					{
						(*tabu[pom.getostatni()]).setkolor(1);
						(*tabu[pom.getostatni()]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
						(*tabu[i]).setkolor(2);
						if (i == 28 || i == 29 || i == 30 || i == 31)
						{
							(*tabu[i]).setkrolowa();
							(*tabu[i]).setBitmaps(Bitmap(BITMAP_BLUEQ_ID), Bitmap(BITMAP_BLUEQ_ID));
						}
						else (*tabu[i]).setBitmaps(Bitmap(BITMAP_BLUE_ID), Bitmap(BITMAP_BLUE_ID));
						for (int i = 0; i < 32; i++)
						{
							if ((*tabu[i]).getkolor() == 1)
							{
								(*tabu[i]).setVisible(false);
								(*tabu[i]).invalidate();
							}
						}
						if (abs(pom.getostatni() - i) > 5)   
						{
							if (i > pom.getostatni())  //zbijanie do przodu
							{
								if ((i == 8) || (i == 9) || (i == 10) || (i == 11) || (i == 16) || (i == 17) || (i == 18) || (i == 19) || (i == 24) || (i == 25) || (i == 26) || (i == 27))
								{
									if (i - pom.getostatni() == 9)
									{
										(*tabu[i - 5]).setkolor(1);
										(*tabu[i - 5]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i - 5]).setVisible(false);
										(*tabu[i - 5]).invalidate();
										(*tabu[i - 5]).setkrolowaf();
									}
									else if (i - pom.getostatni() == 7)
									{
										(*tabu[i - 4]).setkolor(1);
										(*tabu[i - 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i - 4]).setVisible(false);
										(*tabu[i - 4]).invalidate();
										(*tabu[i - 4]).setkrolowaf();
									}
								}
								else
								{
									if (i - pom.getostatni() == 9)
									{
										(*tabu[i - 4]).setkolor(1);
										(*tabu[i - 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i - 4]).setVisible(false);
										(*tabu[i - 4]).invalidate();
										(*tabu[i - 4]).setkrolowaf();
									}
									else if (i - pom.getostatni() == 7)
									{
										(*tabu[i - 3]).setkolor(1);
										(*tabu[i - 3]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i - 3]).setVisible(false);
										(*tabu[i - 3]).invalidate();
										(*tabu[i - 3]).setkrolowaf();
									}
								}
							}
							else if (i < pom.getostatni())    //zbijanie do tylu
							{
								if ((i == 8) || (i == 9) || (i == 10) || (i == 11) || (i == 16) || (i == 17) || (i == 18) || (i == 19) || (i == 0) || (i == 1) || (i == 2) || (i == 3))
								{
									if (pom.getostatni() - i == 9)
									{
										(*tabu[i + 4]).setkolor(1);
										(*tabu[i + 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i + 4]).setVisible(false);
										(*tabu[i + 4]).invalidate();
										(*tabu[i + 4]).setkrolowaf();
									}
									else if (pom.getostatni() - i == 7)
									{
										(*tabu[i + 3]).setkolor(1);
										(*tabu[i + 3]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i + 3]).setVisible(false);
										(*tabu[i + 3]).invalidate();
										(*tabu[i + 3]).setkrolowaf();
									}
								}
								else
								{
									if (pom.getostatni() - i == 9)
									{
										(*tabu[i + 5]).setkolor(1);
										(*tabu[i + 5]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i + 5]).setVisible(false);
										(*tabu[i + 5]).invalidate();
										(*tabu[i + 5]).setkrolowaf();
									}
									else if (pom.getostatni() - i == 7)
									{
										(*tabu[i + 4]).setkolor(1);
										(*tabu[i + 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i + 4]).setVisible(false);
										(*tabu[i + 4]).invalidate();
										(*tabu[i + 4]).setkrolowaf();
									}
								}
							}
						}
						pom.setwykt();
					}
					else
					{
						pom.setwykf();
						pom.setklikf();
						for (int i = 0; i < 32; i++)
						{
							if ((*tabu[i]).getkolor() == 1)
							{
								(*tabu[i]).setVisible(false);
								(*tabu[i]).invalidate();
							}
						}
					}
				}
			}
			//dla czerwonego
			else if ((((*tabu[i]).getkolor() == 0) && (pom.getklik() == false)) || (((*tabu[pom.getostatni()]).getkolor() == 0) && (pom.getklik() == true)))
			{
				//pierwszy klik
				if (pom.getklik() == false)
				{
					pom.setost(i);
					(*tabu[i]).setVisible(false);
					(*tabu[i]).invalidate();
					//jedna sciana boczna
					if ((i % 8 == 0) && (i>0))
					{
						if ((((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1)) || (((*tabu[i + 4]).getkolor() == 2) && (i < 24) && ((*tabu[i + 9]).getkolor() == 1)))
						{
							if (((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 4]).getkolor() == 2) && (i < 24) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
						}
						else if ((*tabu[i - 4]).getkolor() == 1)
						{
							(*tabu[i - 4]).setVisible(true);
							(*tabu[i - 4]).invalidate();
							pom.setwykt();
						}
					}
					//druga sciana boczna
					else if (i == 7 || i == 15 || i == 23 || i == 31)
					{
						if ((((*tabu[i - 4]).getkolor() == 2) && (i > 7) && ((*tabu[i - 9]).getkolor() == 1)) || (((*tabu[i + 4]).getkolor() == 2) && (i < 31) && ((*tabu[i + 7]).getkolor() == 1)))
						{
							if (((*tabu[i - 4]).getkolor() == 2) && (i > 7) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 4]).getkolor() == 2) && (i < 31) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
						}
						else if ((*tabu[i - 4]).getkolor() == 1)
						{
							(*tabu[i - 4]).setVisible(true);
							(*tabu[i - 4]).invalidate();
							pom.setwykt();
						}
					}
					//druga kolumna od lewej
					else if (i == 4 || i == 12 || i == 20 || i == 28)
					{
						if ((((*tabu[i - 3]).getkolor() == 2) && (i > 4) && ((*tabu[i - 7]).getkolor() == 1)) || (((*tabu[i + 5]).getkolor() == 2) && (i < 28) && ((*tabu[i + 9]).getkolor() == 1)))
						{
							if (((*tabu[i - 3]).getkolor() == 2) && (i > 4) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 5]).getkolor() == 2) && (i < 28) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i - 4]).getkolor() == 1) || ((*tabu[i - 3]).getkolor() == 1))
						{
							if ((*tabu[i - 4]).getkolor() == 1)
							{
								(*tabu[i - 4]).setVisible(true);
								(*tabu[i - 4]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i - 3]).getkolor() == 1)
							{
								(*tabu[i - 3]).setVisible(true);
								(*tabu[i - 3]).invalidate();
								pom.setwykt();
							}
						}
					}
					//druga kolumna od prawej
					else if (i == 11 || i == 19 || i == 27)
					{
						if ((((*tabu[i - 5]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1)) || (((*tabu[i + 3]).getkolor() == 2) && (i < 27) && ((*tabu[i + 7]).getkolor() == 1)))
						{
							if (((*tabu[i - 5]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 3]).getkolor() == 2) && (i < 27) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i - 4]).getkolor() == 1) || ((*tabu[i - 5]).getkolor() == 1))
						{
							if ((*tabu[i - 4]).getkolor() == 1)
							{
								(*tabu[i - 4]).setVisible(true);
								(*tabu[i - 4]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i - 5]).getkolor() == 1)
							{
								(*tabu[i - 5]).setVisible(true);
								(*tabu[i - 5]).invalidate();
								pom.setwykt();
							}
						}
					}
					//start czerwonych
					else if (i == 29 || i == 30)
					{
						if ((((*tabu[i - 3]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1)) || (((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1)))
						{
							if (((*tabu[i - 3]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i - 3]).getkolor() == 1) || ((*tabu[i - 4]).getkolor() == 1))
						{
							if ((*tabu[i - 4]).getkolor() == 1)
							{
								(*tabu[i - 4]).setVisible(true);
								(*tabu[i - 4]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i - 3]).getkolor() == 1)
							{
								(*tabu[i - 3]).setVisible(true);
								(*tabu[i - 3]).invalidate();
								pom.setwykt();
							}
						}
					}
					//start czerwonych, linia druga
					else if (i == 25 || i == 26)
					{
						if ((((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1)) || (((*tabu[i - 5]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1)))
						{
							if (((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 5]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i - 4]).getkolor() == 1) || ((*tabu[i - 5]).getkolor() == 1))
						{
							if ((*tabu[i - 4]).getkolor() == 1)
							{
								(*tabu[i - 4]).setVisible(true);
								(*tabu[i - 4]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i - 5]).getkolor() == 1)
							{
								(*tabu[i - 5]).setVisible(true);
								(*tabu[i - 5]).invalidate();
								pom.setwykt();
							}
						}
					}
					//druga linia od konca
					else if (i == 5 || i == 6)
					{
						if ((((*tabu[i + 4]).getkolor() == 2) && ((*tabu[i + 7]).getkolor() == 1)) || (((*tabu[i + 5]).getkolor() == 2) && ((*tabu[i + 9]).getkolor() == 1)))
						{
							if (((*tabu[i + 4]).getkolor() == 2) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 5]).getkolor() == 2) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i - 3]).getkolor() == 1) || ((*tabu[i - 4]).getkolor() == 1))
						{
							if ((*tabu[i - 3]).getkolor() == 1)
							{
								(*tabu[i - 3]).setVisible(true);
								(*tabu[i - 3]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i - 4]).getkolor() == 1)
							{
								(*tabu[i - 4]).setVisible(true);
								(*tabu[i - 4]).invalidate();
								pom.setwykt();
							}
						}
					}
					//srodek co 4 i 5
					else if (i == 9 || i == 10 || i == 17 || i == 18)
					{
						if ((((*tabu[i - 5]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1)) || (((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1)) || (((*tabu[i + 3]).getkolor() == 2) && ((*tabu[i + 7]).getkolor() == 1)) || (((*tabu[i + 4]).getkolor() == 2) && ((*tabu[i + 9]).getkolor() == 1)))
						{
							if (((*tabu[i - 5]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 3]).getkolor() == 2) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 4]).getkolor() == 2) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i - 5]).getkolor() == 1) || ((*tabu[i - 4]).getkolor() == 1))
						{
							if ((*tabu[i - 5]).getkolor() == 1)
							{
								(*tabu[i - 5]).setVisible(true);
								(*tabu[i - 5]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i - 4]).getkolor() == 1)
							{
								(*tabu[i - 4]).setVisible(true);
								(*tabu[i - 4]).invalidate();
								pom.setwykt();
							}
						}
					}
					//srodek co 3 i 4
					else if (i == 13 || i == 14 || i == 21 || i == 22)
					{
						if ((((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1)) || (((*tabu[i - 3]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1)) || (((*tabu[i + 5]).getkolor() == 2) && ((*tabu[i + 9]).getkolor() == 1)) || (((*tabu[i + 4]).getkolor() == 2) && ((*tabu[i + 7]).getkolor() == 1)))
						{
							if (((*tabu[i - 4]).getkolor() == 2) && ((*tabu[i - 9]).getkolor() == 1))
							{
								(*tabu[i - 9]).setVisible(true);
								(*tabu[i - 9]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i - 3]).getkolor() == 2) && ((*tabu[i - 7]).getkolor() == 1))
							{
								(*tabu[i - 7]).setVisible(true);
								(*tabu[i - 7]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 5]).getkolor() == 2) && ((*tabu[i + 9]).getkolor() == 1))
							{
								(*tabu[i + 9]).setVisible(true);
								(*tabu[i + 9]).invalidate();
								pom.setwykt();
							}
							if (((*tabu[i + 4]).getkolor() == 2) && ((*tabu[i + 7]).getkolor() == 1))
							{
								(*tabu[i + 7]).setVisible(true);
								(*tabu[i + 7]).invalidate();
								pom.setwykt();
							}
						}
						else if (((*tabu[i - 4]).getkolor() == 1) || ((*tabu[i - 3]).getkolor() == 1))
						{
							if ((*tabu[i - 4]).getkolor() == 1)
							{
								(*tabu[i - 4]).setVisible(true);
								(*tabu[i - 4]).invalidate();
								pom.setwykt();
							}
							if ((*tabu[i - 3]).getkolor() == 1)
							{
								(*tabu[i - 3]).setVisible(true);
								(*tabu[i - 3]).invalidate();
								pom.setwykt();
							}
						}
					}
				}
				//drugi klik
				else if (pom.getklik() == true)
				{
					if ((*tabu[i]).getkolor() == 1)                //ruch
					{
						(*tabu[pom.getostatni()]).setkolor(1);
						(*tabu[pom.getostatni()]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
						(*tabu[i]).setkolor(0);
						if (i == 0 || i == 1 || i == 2 || i == 3)
						{
							(*tabu[i]).setkrolowa();
							(*tabu[i]).setBitmaps(Bitmap(BITMAP_REDQ_ID), Bitmap(BITMAP_REDQ_ID));
						}
						else (*tabu[i]).setBitmaps(Bitmap(BITMAP_RED_ID), Bitmap(BITMAP_RED_ID));
						for (int i = 0; i < 32; i++)
						{
							if ((*tabu[i]).getkolor() == 1)
							{
								(*tabu[i]).setVisible(false);
								(*tabu[i]).invalidate();
							}
						}
						if (abs(pom.getostatni() - i) > 5)
						{
							if (i < pom.getostatni())  //zbijanie do przodu
							{
								if ((i == 8) || (i == 9) || (i == 10) || (i == 11) || (i == 16) || (i == 17) || (i == 18) || (i == 19) || (i == 0) || (i == 1) || (i == 2) || (i == 3))
								{
									if (pom.getostatni() - i == 9)
									{
										(*tabu[i + 4]).setkolor(1);
										(*tabu[i + 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i + 4]).setVisible(false);
										(*tabu[i + 4]).invalidate();
										(*tabu[i + 4]).setkrolowaf();
									}
									else if (pom.getostatni() - i == 7)
									{
										(*tabu[i + 3]).setkolor(1);
										(*tabu[i + 3]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i + 3]).setVisible(false);
										(*tabu[i + 3]).invalidate();
										(*tabu[i + 3]).setkrolowaf();
									}
								}
								else
								{
									if (pom.getostatni() - i == 9)
									{
										(*tabu[i + 5]).setkolor(1);
										(*tabu[i + 5]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i + 5]).setVisible(false);
										(*tabu[i + 5]).invalidate();
										(*tabu[i + 5]).setkrolowaf();
									}
									else if (pom.getostatni() - i == 7)
									{
										(*tabu[i + 4]).setkolor(1);
										(*tabu[i + 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i + 4]).setVisible(false);
										(*tabu[i + 4]).invalidate();
										(*tabu[i + 4]).setkrolowaf();
									}
								}
							}
							else if (i > pom.getostatni())    //zbijanie do tylu
							{
								if ((i == 8) || (i == 9) || (i == 10) || (i == 11) || (i == 16) || (i == 17) || (i == 18) || (i == 19) || (i == 24) || (i == 25) || (i == 26) || (i == 27))
								{
									if (i - pom.getostatni() == 9)
									{
										(*tabu[i - 5]).setkolor(1);
										(*tabu[i - 5]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i - 5]).setVisible(false);
										(*tabu[i - 5]).invalidate();
										(*tabu[i - 5]).setkrolowaf();
									}
									else if (i - pom.getostatni() == 7)
									{
										(*tabu[i - 4]).setkolor(1);
										(*tabu[i - 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i - 4]).setVisible(false);
										(*tabu[i - 4]).invalidate();
										(*tabu[i - 4]).setkrolowaf();
									}
								}
								else
								{
									if (i - pom.getostatni() == 9)
									{
										(*tabu[i - 4]).setkolor(1);
										(*tabu[i - 4]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i - 4]).setVisible(false);
										(*tabu[i - 4]).invalidate();
										(*tabu[i - 4]).setkrolowaf();
									}
									else if (i - pom.getostatni() == 7)
									{
										(*tabu[i - 3]).setkolor(1);
										(*tabu[i - 3]).setBitmaps(Bitmap(BITMAP_GREEN_ID), Bitmap(BITMAP_GREEN_ID));
										(*tabu[i - 3]).setVisible(false);
										(*tabu[i - 3]).invalidate();
										(*tabu[i - 3]).setkrolowaf();
									}
								}
							}
						}
						pom.setwykt();
					}
					else
					{
						pom.setwykf();
						pom.setklikf();
						for (int i = 0; i < 32; i++)
						{
							if ((*tabu[i]).getkolor() == 1)
							{
								(*tabu[i]).setVisible(false);
								(*tabu[i]).invalidate();
							}
						}
					}
				}
			}
			if (pom.getwyk() == true)
			{
				pom.setklik();
				pom.setwykf();
			}
			else
			{
				(*tabu[pom.getostatni()]).setVisible(true);
				(*tabu[pom.getostatni()]).invalidate();
			}
			break;
		}
	}
}
